CREATE DATABASE teste_3;
USE teste_3;


CREATE TABLE Operadoras_Ativas (
	id INT AUTO_INCREMENT PRIMARY KEY,
    Registro_ANS VARCHAR(6),
    CNPJ VARCHAR(14) NOT NULL,
    Razao_Social VARCHAR(255) NOT NULL,
    Nome_Fantasia VARCHAR(255),
    Modalidade  VARCHAR(255),
    Logradouro  VARCHAR(255),
    Numero  VARCHAR(255),
    Complemento  VARCHAR(255),
	Bairro  VARCHAR(255),
    Cidade  VARCHAR(255),
    UF  VARCHAR(2),
    CEP  CHAR(8),
    DDD  VARCHAR(2),
    TELEFONE VARCHAR(18),
    FAX  VARCHAR(15),
    Endereco_eletronico  VARCHAR(255),
    Representante  VARCHAR(255),
    Cargo_Representante  VARCHAR(255),
    Regiao_de_Comercializacao  VARCHAR(1),
    Data_Registro_ANS DATE
    
);

CREATE TABLE Dados_abertos (
	id INT AUTO_INCREMENT PRIMARY KEY,
	DATA_OPERACAO DATE,
    REG_ANS VARCHAR(6),
    CD_CONTA_CONTABIL VARCHAR(9),
    DESCRICAO VARCHAR(250),
    VL_SALDO_INICIAL DECIMAL(15,2) NULL,
    VL_SALDO_FINAL DECIMAL(15,2) NULL 
);

# Carregar dados para a tabela Operadoras_Ativas
LOAD DATA INFILE 'D:/dados/Relatorio_cadop.csv'
INTO TABLE Operadoras_Ativas
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(Registro_ANS, CNPJ, Razao_Social, Nome_Fantasia, Modalidade, Logradouro, Numero, Complemento, Bairro, Cidade, UF, CEP, DDD, TELEFONE, FAX, Endereco_eletronico, Representante, Cargo_Representante, Regiao_de_Comercializacao, Data_Registro_ANS);

# Carregar dados para a tabela Dados_abertos:
-- Primeiro trimestre de 2023
LOAD DATA INFILE 'D:/dados/2023/1T2023.csv'
INTO TABLE Dados_abertos
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(DATA_OPERACAO, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
	VL_SALDO_INICIAL = IF(@VL_SALDO_INICIAL = '', NULL, CAST(REPLACE(@VL_SALDO_INICIAL, ',', '.') AS DECIMAL(15,2))),
	VL_SALDO_FINAL = IF(@VL_SALDO_FINAL = '', NULL, CAST(REPLACE(@VL_SALDO_FINAL, ',', '.') AS DECIMAL(15,2)));

-- Segundo trimestre de 2023
LOAD DATA INFILE 'D:/dados/2023/2t2023.csv'
INTO TABLE Dados_abertos
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(DATA_OPERACAO, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
	VL_SALDO_INICIAL = IF(@VL_SALDO_INICIAL = '', NULL, CAST(REPLACE(@VL_SALDO_INICIAL, ',', '.') AS DECIMAL(15,2))),
	VL_SALDO_FINAL = IF(@VL_SALDO_FINAL = '', NULL, CAST(REPLACE(@VL_SALDO_FINAL, ',', '.') AS DECIMAL(15,2)));

-- Terceiro trimestre de 2023
LOAD DATA INFILE 'D:/dados/2023/3T2023.csv'
INTO TABLE Dados_abertos
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(DATA_OPERACAO, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
	VL_SALDO_INICIAL = IF(@VL_SALDO_INICIAL = '', NULL, CAST(REPLACE(@VL_SALDO_INICIAL, ',', '.') AS DECIMAL(15,2))),
	VL_SALDO_FINAL = IF(@VL_SALDO_FINAL = '', NULL, CAST(REPLACE(@VL_SALDO_FINAL, ',', '.') AS DECIMAL(15,2)));

-- Quarto trimestre de 2023
LOAD DATA INFILE 'D:/dados/2023/4T2023.csv'
INTO TABLE Dados_abertos
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA_OPERACAO, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
	VL_SALDO_INICIAL = IF(@VL_SALDO_INICIAL = '', NULL, CAST(REPLACE(@VL_SALDO_INICIAL, ',', '.') AS DECIMAL(15,2))),
	VL_SALDO_FINAL = IF(@VL_SALDO_FINAL = '', NULL, CAST(REPLACE(@VL_SALDO_FINAL, ',', '.') AS DECIMAL(15,2))),
    DATA_OPERACAO = STR_TO_DATE(REPLACE(@DATA_OPERACAO, '/', '-'), '%d-%m-%Y');
    
# ------------------------------------------- 2024 --------------------------------- #

-- Primeiro trimestre de 2024
LOAD DATA INFILE 'D:/dados/2024/1T2024.csv'
INTO TABLE Dados_abertos
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(DATA_OPERACAO, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
	VL_SALDO_INICIAL = IF(@VL_SALDO_INICIAL = '', NULL, CAST(REPLACE(@VL_SALDO_INICIAL, ',', '.') AS DECIMAL(15,2))),
	VL_SALDO_FINAL = IF(@VL_SALDO_FINAL = '', NULL, CAST(REPLACE(@VL_SALDO_FINAL, ',', '.') AS DECIMAL(15,2)));

-- Segundo trimestre de 2024
LOAD DATA INFILE 'D:/dados/2024/2T2024.csv'
INTO TABLE Dados_abertos
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(DATA_OPERACAO, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
	VL_SALDO_INICIAL = IF(@VL_SALDO_INICIAL = '', NULL, CAST(REPLACE(@VL_SALDO_INICIAL, ',', '.') AS DECIMAL(15,2))),
	VL_SALDO_FINAL = IF(@VL_SALDO_FINAL = '', NULL, CAST(REPLACE(@VL_SALDO_FINAL, ',', '.') AS DECIMAL(15,2)));

-- Terceiro trimestre de 2024
LOAD DATA INFILE 'D:/dados/2024/3T2024.csv'
INTO TABLE Dados_abertos
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(DATA_OPERACAO, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
	VL_SALDO_INICIAL = IF(@VL_SALDO_INICIAL = '', NULL, CAST(REPLACE(@VL_SALDO_INICIAL, ',', '.') AS DECIMAL(15,2))),
	VL_SALDO_FINAL = IF(@VL_SALDO_FINAL = '', NULL, CAST(REPLACE(@VL_SALDO_FINAL, ',', '.') AS DECIMAL(15,2)));

-- Quarto trimestre de 2024
LOAD DATA INFILE 'D:/dados/2024/4T2024.csv'
INTO TABLE Dados_abertos
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(DATA_OPERACAO, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
	VL_SALDO_INICIAL = IF(@VL_SALDO_INICIAL = '', NULL, CAST(REPLACE(@VL_SALDO_INICIAL, ',', '.') AS DECIMAL(15,2))),
	VL_SALDO_FINAL = IF(@VL_SALDO_FINAL = '', NULL, CAST(REPLACE(@VL_SALDO_FINAL, ',', '.') AS DECIMAL(15,2)));


-- -----------10 operadoras com maiores despesas no ultimo trimestre-----------------
SELECT 
    ROW_NUMBER() OVER (ORDER BY SUM((d.VL_SALDO_FINAL) - (d.VL_SALDO_INICIAL)) DESC) AS Posicao,
    o.Razao_Social
FROM Dados_abertos d
JOIN Operadoras_Ativas o ON o.Registro_ANS = d.REG_ANS
WHERE d.DESCRICAO = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR ' 
  AND d.DATA_OPERACAO = '2024-10-01'
GROUP BY o.Razao_Social
ORDER BY Posicao
LIMIT 10;

-- -----------10 operadoras com maiores despesas no ultimo ano-----------------
SELECT 
    ROW_NUMBER() OVER (ORDER BY SUM((d.VL_SALDO_FINAL) - (d.VL_SALDO_INICIAL)) DESC) AS Posicao,
    o.Razao_Social
FROM Dados_abertos d
JOIN Operadoras_Ativas o ON o.Registro_ANS = d.REG_ANS
WHERE d.DESCRICAO = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR ' 
  AND d.DATA_OPERACAO BETWEEN '2024-01-01' AND '2024-10-01'
GROUP BY o.Razao_Social
ORDER BY Posicao
LIMIT 10;



